
// Do commit this

module.exports = {
    mongoURI: process.env.MONGO_URI,
    cookieKey: process.env.COOKIE_KEY,

    JWT_KEY: process.env.JWT_KEY,


    RECAPTCHA_SITE_KEY: process.env.RECAPTCHA_SITE_KEY,
    RECAPTCHA_SECRET_KEY: process.env.RECAPTCHA_SECRET_KEY,

    GOOGLE_EMAIL_ACCESS_TOKEN: process.env.GOOGLE_EMAIL_ACCESS_TOKEN,
    GOOGLE_EMAIL_CLIENT_ID: process.env.GOOGLE_EMAIL_CLIENT_ID,
    GOOGLE_EMAIL_CLIENT_SECRET: process.env.GOOGLE_EMAIL_CLIENT_SECRET,
    GOOGLE_EMAIL_REFRESH_TOKEN: process.env.GOOGLE_EMAIL_REFRESH_TOKEN,

    ADMIN_SECRET_CODE: process.env.ADMIN_SECRET_CODE,

    CLOUDINARY_KEY_NAME: process.env.CLOUDINARY_KEY_NAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET_KEY: process.env.CLOUDINARY_API_SECRET_KEY,

    HTTP_NAME: process.env.HTTP_NAME,
    KEVIN_EMAIL: process.env.KEVIN_EMAIL,
};