
export default () => {
    return [
            {  
                name="James Endicott",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="James Gung",
                img="../../assets/people/james_gung.jpg",
                imgx="",
                imgy="",
                title="",
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="Ghazaleh Kazeminejad",
                img="../../assets/people/ghazelah_kazeminejad.jpg",
                imgx="100",
                imgy="134",
                title="",
                dept="Linguistics", 
                info="",
                email="",
                phone="",
            },
            {
                name="Ling Liu",
                img="../../assets/people/ling_liu.jpg",
                imgx="100",
                imgy="134",
                title="",
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="Skatje Myers",
                img="../../assets/people/skatje_myers.jpg",
                imgx="100",
                imgy="129",
                title="",
                dept="Computer Science",
                info="Specialization / Interests: NLP, machine learning",
                email="",
                phone="",
            },
            {
                name="Tim O'Gorman",
                img="../../assets/people/tim_ogorman.jpg",
                imgx="100",
                imgy="133",
                title="",
                dept="Linguistics",
                info="",
                email="",
                phone="",
            },
            {
                name="Daniel Peterson",
                img="../../assets/people/daniel_peterson.jpg",
                imgx="",
                imgy="",
                title="" ,
                dept="" ,
                info="" ,
                email="" ,
                phone="",
            },
            {
                name="Kevin Stowe",
                img="../../assets/people/kevin_stowe.jpg",
                imgx="100",
                imgy="133",
                title="",
                dept="Linguistics",
                info="Specialization / Interests: Computational semantics, machine learning, metaphor detection and interpretation, NLP for social media",
                email="",
                phone="",
            },
            {
                name="Abhijit Suresh",
                img="../../assets/people/abhijit_suresh.jpg",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: Cognitive Artificial Intelligence (Interdisciplinary)",
                email="",
                phone="",
            },
    ]
}
