
export default () => {
    return [
            {  
                name="Lee Becker", 
                img="",
                imgx="",
                imgy="",
                title="",
                dept="",
                info="Specialization / Interests: Natural Language Processing, Computational Semantics, Intelligent Tutoring Systems, Dialogue Management, Question Generation, Educational Data Mining",
                email="",
                phone="",
            },
            {
                name="Lee Becker",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="", 
                info="Specialization / Interests: Natural Language Processing, Computational Semantics, Intelligent Tutoring Systems, Dialogue Management, Question Generation, Educational Data Mining",
                email="", 
                phone="",
            },
            {
                name="Chih How Bong",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests : Text Classification, Information Retrieval, Natural Language Processing, Intelligence Tutoring Systems Current Position: Faculty of Computer Science and Information Technology, University Malaysia Serawak",
                email="",
                phone="",
            },
            {
                name="Claire Bonial",
                img="https://www.colorado.edu/lab/clear/sites/default/files/styles/small_thumbnail/public/people/claire_bonial.jpeg?itok=4ZBlWqHS",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="Daniel Cer",
                img="",
                imgx="",
                imgy="",
                title="",
                dept="",
                info="Current position : Postdoctoral Researcher Stanford University",
                email="",
                phone="",
            },
            {
                name="Wei-Te Chen",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="Computer Science",
                info="Specialization / Interests: Semantic Parsing, Machine Translation, Semantic Role Labelling, Annotation Tool Design",
                email="",
                phone="",
            },
            {
                name="Ying Chen",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Current position : Associate Professor China Agricultural University",
                email="", 
                phone="",
            },
            {
                name="Jinho Choi",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests : Dependency Parsing, Semantic Role Labelling, Machine Translation Current Position: Assistant Professor Emory University",
                email="",
                phone="",
            },
            {
                name="Katie Conger", 
                img="",
                imgx="",
                imgy="",
                title="Research Assistant",
                dept="",
                info="",
                email="kathryn.conger@colorado.edu",
                phone="",
            },
            {
                name="William Corvey",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: Discourse Processing, Computer Mediated Communication",
                email="",
                phone="",
            },
            {
                name="Sebastian De la Chica",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Current position : Senior Applied Researcher, Bing Microsoft",
                email="",
                phone="",
            },
            {
                name="Dimitriy Dligach",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: Efficient Annotation Current Position Researcher Harvard Medical School, Childern's Hospital, Boston",
                email="",
                phone="",
            },
            {
                name="Nicholas Dronen", 
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="Ahmad Faisal", 
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Current Position Google", 
                email="",
                phone="",
            },
            {
                name="Bill Foland",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="Computer Science", 
                info="",
                email="",
                phone="",
            },
            {
                name="Maha Foster",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: Language Acquisition",
                email="",
                phone="",
            },
            {
                name="Meredith Green",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant",
                dept="",
                info="",
                email="meredithgrrrl@gmail.com",
                phone="",
            },
            {
                name="Alvin Grissom II",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="Computer Science",
                info="",
                email="", 
                phone="",
            },
            {
                name="Shudong Hao",
                img="",
                imgx="",
                imgy="",
                title="",
                dept="Computer Science",
                info="",
                email="" ,
                phone="",
            },
            {
                name="Jena Hwang",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: Computational Linguistics / NLP Current Position Resarch Associate Florida Institute for Human and Machine Cognition Oracle",
                email="",
                phone="",
            },
            {
                name="Kirill Kireyev",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Current position : Founder, Instagrok",
                email="",
                phone="",
            },
            {
                name="Praful Mangalath",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Current position : Prismatic", 
                email="",
                phone="",
            },
            {
                name="Aous Mansouri",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: Semitic linguistics, semantics, tense and aspect - specifically imperfective constructions, Arabic dialectology",
                email="",
                phone="",
            },
            {
                name="Keith Maull",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: Educational Informatics, Data Mining, Computational Models of Pedagogy in Digital Learning Contexts",
                email="",
                phone="",
            },
            {
                name="Philip Ogren",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: My dissertation focused on syntactic coordination resolution in the biomedical domain using machine learning and language modeling. I enjoy building open source solutions for natural language processing tasks and am a contributor to several open source projects including ClearTK and uimaFIT. Current Position : Oracle",
                email="",
                phone="",
            },
            {
                name="Ifeyinwa Okoye",
                img="https://www.colorado.edu/lab/clear/sites/default/files/styles/small_thumbnail/public/people/ifi_okoye.jpg?itok=-eVRqgVL",
                imgx="100",
                imgy="107",
                title="",
                dept="",
                info="Specialization / Interests: My research interest spans text analytics, natural language processing, adaptive and personalization technology, user modeling and educational technology such as intelligent tutoring systems.",
                email="",
                phone="",
            },
            {
                name="Sameer Pradhan",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Current position : Researcher Harvard Medical School, Children's Hospital, Boston",
                email="",
                phone="",
            },
            {
                name="Forough Poursabzi-Sangdeh"; 
                img="";
                imgx="";
                imgy="";
                title="";
                dept="Computer Science";
                info="Specialization / Interests: NLP, machine learning, interacting with humans for improving machine learning and NLP algorithms";
                email="";
                phone="";
            },
            {
                name="Franco Salvetti";
                img="";
                imgx="";
                imgy="";
                title=""; 
                dept=""; 
                info="Current position : Principal Software Engineer, Bing Microsoft"; 
                email=""; 
                phone="";
            },
            {
                name="William Styler",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: Acoustic and articulatory phonetics, vowels and vowel perception, speaker normalization, speech perception, computerized speech measurement techniques, phonology, medical speech and terminology analysis, UMLS entity and relation annotation and automated medical-record analysis. Current Position : Postdoctoral Researcher University of Michigan",
                email="",
                phone="",
            },
            {
                name="Arafat Sultan",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="Psychology", 
                info="",
                email="", 
                phone="",
            },
            {
                name="Ashwini Vaidya",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: Computational Linguistics &amp; Corpus Linguistics Current Position : Postdoctoral fellowship IIT-Delhi",
                email="",
                phone="",
            },
            {
                name="Sudha Verma",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="", 
                info="Specialization / Interests: NLP, Web/Social Media, Information Extraction for crisis events",
                email="",
                phone="",
            },
            {
                name="Philipp Wetzler", 
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="",
                info="Specialization / Interests: Natural Language Processing, Computational Semantics, Machine Learning, Document Quality, Digital Libraries Current Position : Google",
                email="",
                phone="",
            },
            {
                name="Shumin Wu",
                img="",
                imgx="",
                imgy="",
                title="", 
                dept="", 
                info="Specialization / Interests: Machine Translation, Coreference Resolution, Semantic Role Labeling Current Position : Hitachi",
                email="", 
                phone="",
            },
    ]
}
                        
                        <Person 
                           />
                        
                        <Person 
                            />
                        
                        <Person 
                           />