
export default () => {
    return [
            {  
                name="Julia Bonn",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant", 
                dept="",
                info="",
                email="julia.bonn@colorado.edu",
                phone="",
            },
            {
                name="Ahmed Elsayed",
                img="",
                imgx="",
                imgy="",
                title="Research Staff", 
                dept="",
                info="",
                email="ahmed.s.elsayed@colorado.edu", 
                phone="",
            },
            {
                name="Jenette Preciado",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant", 
                dept="",
                info="",
                email="jenette.preciado@colorado.edu", 
                phone="",
            },
            {
                name="Michael Regan",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant",
                dept="",
                info="",
                email="michael.regan@colorado.edu",
                phone="",
            },
            {
                name="Kristin Wright-Bettner",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant",
                dept="",
                info="",
                email="kristin.wrightbettner@colorado.edu",
                phone="",
            },
    ]
}