
export default () => {
    return [
            {  
                name="Muhammed Aitmoulay",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant",
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="James Babani",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant"
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="Robert Bowen",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant",
                dept="",
                info="",
                email="robert.bowen@colorado.edu", 
                phone="",
            },
            {
                name="Kevin Crooks",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant", 
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="George Figgs",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant", 
                dept="",
                info="",
                email="", 
                phone="",
            },
            {
                name="Amanda Howard",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant", 
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="Jacquelynn Montoya",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant", 
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="Nattawut Ngampatipatpong",
                img="",
                imgx="",
                imgy="",
                title="Senior Prof. Research Assistant",
                dept="",
                info="System architecture Design, Database and Software Development (in ICARE, CARLA, ORLA Web and 3D-Animation Project).", 
                email="ngampati@colorado.edu",
                phone="",
            },
            {
                name="Laurell Richey",
                img="",
                imgx="",
                imgy="",
                title="Research Assistant",
                dept="",
                info="Helping create materials, supervising work-study students, and helping elementary students and teachers use the programs well in the schools for ICARE and CARLA Project.",
                email="laurell.richey@colorado.edu",
                phone="",
            },
            {
                name="Luann Sessions", 
                img="",
                imgx="",
                imgy="",
                title="Prof. Research Assistant",
                dept="",
                info="",
                email="",
                phone="",
            },
            {
                name="Taylor Struemph",
                img="",
                imgx="",
                imgy="",
                title="Prof. Research Assistant",
                dept="",
                info="",
                email="taylor.struemph@colorado.edu",
                phone="",
            },
            {
                name="Joel Terrell",
                img="",
                imgx="",
                imgy="",
                title="Prof. Research Assistant", 
                dept="",
                info="Development of creative comprehension questions for CARLA. Content development (exercises, stories, books, interactive scripts, etc) for CARLA. Literacy testing for children Kdg-5. Monitoring and encouraging students. IT services (network and hardware troubleshooting).",
                email="terellj@colorado.edu",
                phone="",
            },
            {
                name="Tammy Tomczyk", 
                img="",
                imgx="",
                imgy="",
                title="Prof. Research Assistant", 
                dept="",
                info="", 
                email="tammy.tomczyk@colorado.edu", 
                phone="",
            },
            {
                name="Jariya Tuantranont",
                img="",
                imgx="",
                imgy="",
                title="Senior Prof. Research Assistant", 
                dept="",
                info="Programming and design User Interfaces, graphics and animation in many projects; (ICARE, CARLA, ORLA Web). Web Master for CLEAR web site.", 
                email="jariya.tuantranont@colorado.edu", 
                phone="",
            },
    ]
}