
export default () => {
    return [
            {  
                name="Susan Brown" ,
                img="../../assets/people/susan_brown.png",
                imgx="",
                imgy="",
                title="Adjunct Assistant Professor",
                dept="Linguistics",
                info="Specialization / Interests: Natural language processing, computational semantics, lexical resources and ontologies.",
                email="",
                phone="",
            },
            {
                name="Mans Hulden",
                img="https://www.colorado.edu/lab/clear/sites/default/files/styles/small_thumbnail/public/people/mans_hulden.png?itok=HG8kUHqS", 
                imgx="",
                imgy="",
                title="Assistant Professor", 
                dept="Linguistics",
                info="Interests: Computational linguistics, natural language processing, computational phonology and morphology, grammatical inference, formal language theory, learnability of natural language, machine learning, and (computational) historical linguistics.",
                email="mans.hulden@colorado.edu" ,
                phone="",
            },
            {
                name="James Martin",
                img="https://www.colorado.edu/lab/clear/sites/default/files/styles/small_thumbnail/public/people/jim_martin_4.cuphoto.jpg?itok=GIUrH6Ig",
                imgx="100",
                imgy="140",
                title="Professor", 
                dept="Computer Science",
                info="Specialization / Interests: Natural language processing and machine learning with applications to computational semantics; cognitive linguistics with a focus on metaphor and other forms of non-literal language", 
                email="james.martin@colorado.edu",
                phone="303 735 5196",
            },
            {
                name="Martha Palmer",
                img="https://www.colorado.edu/lab/clear/sites/default/files/styles/small_thumbnail/public/people/martha.jpg?itok=eenS9nts",
                imgx="100",
                imgy="125",
                title="Professor", 
                dept="Linguistics and Computer Science",
                info="",
                email="martha.palmer@colorado.edu",
                phone="303 735 3027",
            },
            {
                name="Michael Paul",
                img="https://www.colorado.edu/lab/clear/sites/default/files/styles/small_thumbnail/public/people/michael_paul.jpg?itok=S64s_2hj",
                imgx="100",
                imgy="121",
                title="Assistant Professor",
                dept="Information Science",
                info="Interests: Topic modeling, exploratory machine learning, social media analysis, computational social science, health informatics.",
                email="michael.j.paul@colorado.edu",
                phone="",
            },
            {
                name="Tammy Sumner",
                img="https://www.colorado.edu/lab/clear/sites/default/files/styles/small_thumbnail/public/people/tamara_sumner.png?itok=i9-mVOBY",
                imgx="100",
                imgy="117",
                title="Professor • Directory of ICS", 
                dept="Cognitive Science Institute • Computer Science", 
                info="",
                email="tammy.sumner@colorado.edu", 
                phone="303 735 4469",            
            },
            {
                name="Sarel Van Vuuren",
                img="../../assets/people/sarel_van_vuuren.jpg",
                imgx="100",
                imgy="134",
                title="Associate Research Professor",
                dept="Cognitive Science Institute",
                info="",
                email="sarel.vanvuuren@colorado.edu", 
                phone="303 735 5265",
            },
            {
                name="Wayne Ward",
                img="../../assets/people/wayne_ward.jpg",
                imgx="",
                imgy="",
                title="Research Professor",
                dept="Computational Language and Education Research",
                info="",
                email="wayne.ward@colorado.edu", 
                phone="303 735 5070",
            },
    ]
}
